version: '3'
services:
  backend:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    depends_on:
      - database
    restart: always

    networks:
      - mynetwork

  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

    restart: always

    networks:
      - mynetwork

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: Employee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456a
    ports:
      - "5434:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge