name: CI

on:
  push:
    branches: [ main ]
    paths:
         - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
         - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./Angular-10-Spring-Boot-CRUD-App/

      - name: Test frontend
        run: npm test
        working-directory: ./Angular-10-Spring-Boot-CRUD-App/
        
      - name: Build application
        run: npm run build
        working-directory: ./Angular-10-Spring-Boot-CRUD-App/

